version: '3'
services:
  postgres:
    image: postgres:9.4.1
  web:
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: postgres
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
    volumes:
      - .:/app
